apiVersion: v1
stringData:
  db_name : "postgres"
  db_host : "192.168.0.3"
  db_port : "5432"
  db_user : "postgres"
  db_password : # Replace with your password
  users_path: "http://service-users"
  offers_path: "http://service-offers"
  posts_path: "http://service-posts"
  routes_path: "http://service-routes"
  scores_path: "http://service-scores"
kind: Secret
metadata:
  name: app-secrets